### ISSUE TITLE
可以使用火狐浏览器吗？

### ISSUE THREAD

**Issue by HaibaraZ3R0** [Levitans/-#10]
用火狐报了这个错
![uTools_1647689408852](https://user-images.githubusercontent.com/79103412/159119389-44ce917b-6c40-4c84-a089-7e64df8fce13.png)

**Comment by HaibaraZ3R0** [comment]
换了谷歌浏览器也会报错![uTools_1647690612792](https://user-images.githubusercontent.com/79103412/159119919-a49e7fce-3395-4e00-b351-8a5152f95ec3.png)

**Comment by Levitans** [comment]
用火狐确实会出问题我也不知道为什么，我是用谷歌开发的。
你第二个截图，明显报错是因为没找到元素，证明你的课程页面和我的是不一样的，你可以看一下“使用说明.md”里面的第四点
