### ISSUE TITLE
package/bin/unzip.exe 这个是干什么的？

### ISSUE THREAD

**Issue by xcc-1921** [Levitans/-#25]
虽然很感谢大佬，但是这个exe是干什么的？我找了一圈没看到注释

ps:实际上我自己已经搭了一个架子，就是差一点代码不确定怎么写，在这里倒是找到了。感谢感谢

**Comment by Levitans** [comment]
这个是用来解压zip包的，主要是在“程序更新.cmd”文件里面调用了这个unzip.exe。
程序更新的原理就是从github仓库上下载项目的压缩包，然后在解压替换本地的源码，所以需要这个unzip.exe。
但是好像“程序更新.cmd”和“程序运行.cmd”这两个文件从github上下载下来是乱码的（还没搞懂为什么上传后下载会乱码），不能直接运行需要手动转成gbk或gb2312。

**Comment by xcc-1921** [comment]
好的，谢谢
